{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red224\green232\blue240;\red162\green172\blue183;}
{\*\expandedcolortbl;;\cssrgb\c90196\c92941\c95294;\cssrgb\c69412\c72941\c76863\c7843;}
\paperw11900\paperh16840\margl1440\margr1440\vieww34000\viewh21380\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: 0.2\
\
phases:\
  pre_build:\
    commands:\
      - echo Logging in to Amazon ECR...\
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 847245319109.dkr.ecr.ap-south-1.amazonaws.com\
      - echo Checking if Dockerfile exists...\
      - ls -al\
  build:\
    commands:\
      - echo Build started on `date`\
      - echo Building the Docker image...\
      - docker build -t 
\f1\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
Dockerfile
\f0\fs24 \cf0 \cb1 \kerning1\expnd0\expndtw0  .\
  post_build:\
    commands:\
      - echo Build completed on `date`\
      - echo Tagging the Docker image...\
      - docker tag test:latest 847245319109.dkr.ecr.ap-south-1.amazonaws.com/test:latest\
      - echo Pushing the Docker image to ECR...\
      - docker push 847245319109.dkr.ecr.ap-south-1.amazonaws.com/test:latest\
artifacts:\
  files: '**/*'\
  discard-paths: yes\
}